name: Build APK

on: [push, pull_request] # سيعمل التحديث تلقائياً عند رفع كود جديد

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Buildozer Action
        uses: ArtemSBulat/buildozer-action@v1
        with:
          buildozer_version: master
          python_version: 3.8
          subcommand: debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: bin/*.apk
