name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        # هذا هو المسار الصحيح لأداة البناء التي تدعم التحديثات الجديدة
        uses: ArtemSerebriennikov/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer android debug

      - name: Upload APK
        # استخدام الإصدار v4 لتفادي أخطاء الرفع التي ظهرت لك
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
