name: Build APK

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # تحديث للإصدار 4

      - name: Build with Buildozer
        uses: ArtemSBulat/buildozer-action@v1 # تأكد من كتابة الاسم هكذا تماماً
        with:
          buildozer_version: master
          python_version: 3.11
          subcommand: debug

      - name: Upload APK
        uses: actions/upload-artifact@v4 # تحديث للإصدار 4 لحل مشكلة deprecation
        with:
          name: ZamilApp-Package
          path: bin/*.apk
